### PR TITLE
Remove unused "asyncblock" dependency

### LINKED ISSUE #8: Remove native dependencies
The goal of this module is to be pure JavaScript, correct? The dependency `asyncblock` requires a compiled, native dependency `fibers`. Can we eliminate this dependency so `airplay-js` is pure-JS again?

### PR DESCRIPTION
**Pull request by feross**
Fixes #8 (Remove native dependencies)

### CODE REVIEW

**Comment by feross** [comment]
Can you do a release on npm?

**Comment by guerrerocarlos** [comment]
Sr Yes Sr! Right Away!

**Comment by feross** [comment]
Thanks! :+1: :smile:

**Comment by guerrerocarlos** [comment]
Done :+1:

**Comment by feross** [comment]
Thanks!

**Pull request merged**
