### PR TITLE
Update mdns-js to latest version

### PR DESCRIPTION
**Pull request by dcposch**
This fixes a warning on newer versions of node:

```
WARN engine mdns-js@0.3.1: wanted: {"node":"^0.10.3 || ^0.12.0"} (current: {"node":"4.2.4","npm":"2.14.12"})
airplay-js@0.2.15 node_modules/airplay-js
├── plist-with-patches@0.5.1 (xmlbuilder@0.4.3, xmldom@0.1.22)
└── mdns-js@0.3.1 (semver@4.3.6, mdns-js-packet@0.1.12)
```

Also:
- Remove code that only works on one person's computer
- Added `npm test`

### CODE REVIEW

**Comment by dcposch** [comment]
Before, the tests had a hardcoded `/Users/fankun/` and `/Users/carlos` ...

**Comment by feross** [comment]
:+1:

**Comment by feross** [comment]
Nice work, @dcposch! Glad that you removed thar GitHub dependency from `package.json` because it causes install troubles for users behind a firewall that only allows port 80 and 443. That's me right now using "Stanford Visitor" Wi-Fi.

After this is merged, it would be nice to publish to npm too, so we can start relying on npm instead of [doing this](https://github.com/feross/webtorrent-app/blob/ebb8d77287f5ab67a466ba67b3f3af42c3dd2809/package.json#L14) in our `package.json`.

Cheers!

**Comment by feross** [comment]
Ping @guerrerocarlos

**Comment by guerrerocarlos** [comment]
Done, and published to npm.

Sorry for the huge delay. Getting back now ;)

**Comment by feross** [comment]
No problem, thanks for getting to this eventually :)

**Pull request merged**
